services:
  webterminal:
    build: .
    network_mode: service:husarnet-webterminal
    # ports:
    #   - 7681:7681

  husarnet-webterminal:
    image: husarnet/husarnet
    devices:
      - /dev/net/tun
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    cap_add:
      - NET_ADMIN
    volumes:
      - /var/lib/husarnet
    environment:
      - HOSTNAME=my-webterminal
      - JOINCODE=${JOINCODE}
    ports:
      - 8080:7681